name: auth-service CI

on:
  push:
    branches-ignore:
      - main

jobs:

  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          cache: maven

      - name: Check code formatting
        run: mvn spotless:check

  test:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          cache: maven
      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run unit tests
        run: mvn test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          cache: maven

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: auth-artifact
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: auth-artifact

      - name: Create target directory
        run: mkdir -p target

      - name: Move JAR to target directory
        run: mv *.jar target/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildX
        uses: docker/setup-buildx-action@v3

      - name: Log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      - name: Cleanup target directory
        run: rm -rf target/